name: Build all functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-functions:
    name: Build Java Lambdas
    strategy:
      matrix:
        function: ['ingest-alerter']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Builder Functions
      run: |
        cd functions/${{ matrix.function }}
        mvn clean package
