name: Build all functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-functions:
    name: Build Java Lambdas

    strategy:
      matrix:
        function: ['ingest-alerter', 'ingest-alert-filter']

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Functions
      run: |
        cd functions/${{ matrix.function }}
        mvn clean package
      env:
        DYNAMODB_HOST: dynamodb
        DYNAMODB_PORT: 8000